### PR TITLE
Major rehaul

### PR DESCRIPTION
**Pull request by TomazErjavec**
- smaller but final subset of novels, with most ELTeC metadata
- new pipeline for ingest and conversion
- slightly different TEI elements
- added original (for now, IMP) files 
- renamed ELTeC files, so the ELTeC id is resolvable to IMP in (rather than just keeping the IMP number)
- changes to REAMDEs
- bits and bobs

### CODE REVIEW

**Comment by lb42** [comment]
Happy to merge your changes -- it's your repository! I'll comment later on the details. For the moment, there's no such word as "rehaul" in English -- you mean "overhaul", I think.

**Comment by TomazErjavec** [comment]
Great, thanks! And sorry about my neologism. Looking forward to your comments!

**Comment by lb42** [comment]
I see you use xml:id all over the place, and with values that are unique only within a single document. That 
causes problems when I try to validate the corpus as a whole. But even if you only process one document at a time, what are the xml:id values used for?

**Comment by TomazErjavec** [comment]
> I see you use xml:id all over the place, and with values that are unique only within a single document.

The source documents weren't really meant to be a corpus, rather they are a DL with each document independent.

> That causes problems when I try to validate the corpus as a whole.

I am not overly attached to IDs in the scope of ELTeC, so just say the word and I will throw them out. Alternativelly, I can simply prefix them with the ID of the document, which would solve the problem as well.

> what are the xml:id values used for?

E.g. for linking from the (autogenerated) ToC in the HTML version of the docs, self-links, etc. By no means all are actually used, my principle is that it is good to have them, and they don't hurt.

**Comment by lb42** [comment]
the word

**Comment by lb42** [comment]
The problem with things that "are good to have and don't hurt" in the eltec context is that we're trying here to define a corpus of material which is marked up with NO SURPRISES. So everything permitted by the markup scheme should be present and used for a purpose. Nothing should be optional; where the TEI offers n different ways to do something, ELTeC will offer just one; where the TEI permits arbitrariness, ELTeC is ruthlessly opposed to variety. Mind you, I already lost one argument around this principle (page breaks) and expect to lose others. But that's why I don't like redundant xml:ids all over the place! If you want to make everyone put them in, fine: let's have that argument. But putting them in here and there is a bad idea.

**Comment by TomazErjavec** [comment]
> the word

Done. Another pull request waiting. As I mentioned, it might be easier if I had push access.

>  a corpus of material which is marked up with NO SURPRISES

Fair enough, will be glad to comply, but as far as I understand the schema is still evolving, so it's hard to know at times what is allowed and what not (and formal validation does not always help). 

I just mention that in my work it was sometimes easier to make a (TEI compatible) schema from scratch, rather tham trying to reduce TEI ODD enough to accept exactly what was needed for the project.

**Comment by lb42** [comment]
I don't know why you don't have push access to the Repo: you should have. If you're not in the "contributors" github group thing, ask Borja to add you. 

The schema is still evolving in the light of what people in WG1 can agree on (you may notice I just posted a short list of six proposed modiications); I am gradually introducing more constraints into it to reflect/enforce the good practice documented in the wiki and the manual, so please bear with me/us. 

I don't understand your last point, but since it's not relevant to this ticket maybe you could explain in a separate email.

**Pull request merged**
